MvcApp2017/ViewModels/FormViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MvcApp2017.ViewModels
{
	public class FormViewModel
	{
		[Required]
		[Display(Name = "Name")]
		public string Name { get; set; }

		[Required]
		[Display(Name = "Email")]
		public string Email { get; set; }

		public FormViewModel()
		{
		}
	}
}

MvcApp2017/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApp2017.ViewModels;
using MvcApp2017.Filters;

namespace MvcApp2017.Controllers
{
	public class ApiController : Controller
	{
		[HttpGet]
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public ActionResult ReadViewModel()
		{
			var vm = new ApiViewModel();
			vm.Id = 1;
			vm.FruitId = 102;
			vm.FruitName = "Orange";
			return Json(new[] { vm });
		}

		[HttpPost]
		public ActionResult UpdateViewModel(ApiViewModel vm)
		{
			return Json(new[] { vm });
		}

		[HttpPost]
		public ActionResult CreateViewModel()
		{
			return Json(new[] { new object() });
		}

		[HttpPost]
		public ActionResult DeleteViewModel()
		{
			return Json(new[] { new object() });
		}

		[HttpPost]
		public ActionResult ReadSelectListOpts()
		{
			var list = new List<SelectListItem>(){
				new SelectListItem(){ Value = "101", Text = "Apple", },
				new SelectListItem(){ Value = "102", Text = "Orange", },
				new SelectListItem(){ Value = "103", Text = "Bannana", },
			};
			return Json(list);
		}
	}

	public class ApiViewModel
	{
		public int Id;
		public int? FruitId;
		public string FruitName;
	}
}

MvcApp2017/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApp2017.ViewModels;
using MvcApp2017.Filters;

namespace MvcApp2017.Controllers
{
	public class FormController : Controller
	{
		[HttpGet]
		public ActionResult Index()
		{
			var viewModel = new FormViewModel();
			viewModel.Name = "Todd";
			viewModel.Email = "foo@bar.baz.biz";
			return View(viewModel);
		}

		[HttpPost]
		[PreventDuplicateRequest(DelayRequest = 1)]
		public ActionResult Index(FormViewModel viewModel)
		{
			if(ViewData.ModelState.ContainsKey("DuplicateRequest"))
			{
			}

			ModelState.Clear();
			TryValidateModel(viewModel);
			return View(viewModel);
		}
	}
}

MvcApp2017/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApp2017.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Contact page.";

			return View();
		}
	}
}

MvcApp2017/Views/Form/Index.cshtml
@model MvcApp2017.ViewModels.FormViewModel
@using MvcApp2017.Extensions

<br>
<br>
@using (Html.BeginForm("Index", "Form", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	if (!ViewData.ModelState.IsValid)
	{
		<p>There are errors</p>
		@Html.ValidationSummaryBootstrap()
	}

	<div class="form-group required">
		<label class="col-sm-4 control-label">
			@Html.DisplayNameFor(m => m.Name)
			<span class="ix_popover_btn glyphicon glyphicon-info-sign" data-toggle="popover" data-content="Representative who will be responsible for this account and receive commissions"></span>
		</label>
		<div class="col-sm-4">
			@Html.TextBoxFor(m => m.Name, new { @class = "form-control", required = "required", maxlength = 255 })
		</div>
	</div>

	<div class="form-group required">
		<label class="col-sm-4 control-label">
			@Html.DisplayNameFor(m => m.Email)
			<span class="ix_popover_btn glyphicon glyphicon-info-sign" data-toggle="popover" data-content="Representative who will be responsible for this account and receive commissions"></span>
		</label>
		<div class="col-sm-4">
			@Html.TextBoxFor(m => m.Email, new { @class = "form-control", required = "required", maxlength = 255 })
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<button type="submit" class="btn btn-primary" formnovalidate>Save</button>
		</div>
	</div>
}

MvcApp2017/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MvcApp2017/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="#">foo@bar.biz</a><br />
    <strong>Marketing:</strong> <a href="#">qux@corge.grault</a>
</address>

MvcApp2017/Views/Home/Index.cshtml
<div class="jumbotron">
	<h1 class="display-3">Hello</h1>
	<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	<hr class="my-4">
	<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	<p class="lead">
		<a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
	</p>
</div>

MvcApp2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title></title>
	@Styles.Render("~/content/css")
</head>
<body>
	<nav class="navbar navbar-inverse navbar-toggleable-md bg-inverse">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		@Html.ActionLink("SandBox", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
				</li>
				<li class="nav-item">
					@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
				</li>
				<li class="nav-item">
					@Html.ActionLink("Form", "Index", "Form", null, new { @class = "nav-link" })
				</li>
				<li class="nav-item">
					@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
				</li>
			</ul>
		</div>
	</nav>

	<div class="container">
		@RenderBody()

		<hr>
		<footer>
			<p>@DateTime.Now.Year</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/app")
	@RenderSection("scripts", required: false)
</body>
</html>